
spring:
  messages:
    encoding: UTF-8
    basename: messages
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: Group0000-
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key : 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

kakao:
  clientId: 25f903148ab4e786405cf2e696cc370c
  callbackUrl:  http://localhost:8080/api/user/kakao/callback